import { db } from "./db";
import { cosmeticItems } from "@shared/schema";

const COSMETIC_ITEMS = [
  // === BACKGROUNDS ===
  {
    name: "Sunset Gradient",
    description: "A warm orange-to-purple gradient background",
    category: "backgrounds",
    rarity: "common",
    price: 50,
    imageUrl: null,
    metadata: { type: "gradient", colors: ["#ff7e5f", "#feb47b", "#7b4397"] },
  },
  {
    name: "Ocean Depths",
    description: "Deep blue oceanic gradient with subtle waves",
    category: "backgrounds",
    rarity: "common",
    price: 50,
    imageUrl: null,
    metadata: { type: "gradient", colors: ["#0f2027", "#203a43", "#2c5364"] },
  },
  {
    name: "Northern Lights",
    description: "Shimmering aurora borealis effect",
    category: "backgrounds",
    rarity: "rare",
    price: 150,
    imageUrl: null,
    metadata: { type: "gradient", colors: ["#00c9ff", "#92fe9d", "#662d8c"] },
  },
  {
    name: "Cosmic Purple",
    description: "Deep space purple with subtle stars",
    category: "backgrounds",
    rarity: "rare",
    price: 150,
    imageUrl: null,
    metadata: { type: "gradient", colors: ["#1a0033", "#4a0080", "#8000ff"], particles: true },
  },
  {
    name: "Emerald Forest",
    description: "Calming green nature-inspired gradient",
    category: "backgrounds",
    rarity: "common",
    price: 75,
    imageUrl: null,
    metadata: { type: "gradient", colors: ["#134e5e", "#71b280"] },
  },
  {
    name: "Midnight Galaxy",
    description: "Stunning galaxy with nebula effects",
    category: "backgrounds",
    rarity: "epic",
    price: 300,
    imageUrl: null,
    metadata: { type: "gradient", colors: ["#0f0c29", "#302b63", "#24243e"], particles: true, nebula: true },
  },
  {
    name: "Rose Gold",
    description: "Elegant rose gold shimmer",
    category: "backgrounds",
    rarity: "rare",
    price: 200,
    imageUrl: null,
    metadata: { type: "gradient", colors: ["#b76e79", "#f7d1d1", "#eac5c5"] },
  },
  {
    name: "Zen Garden",
    description: "Peaceful sage and cream tones",
    category: "backgrounds",
    rarity: "common",
    price: 60,
    imageUrl: null,
    metadata: { type: "gradient", colors: ["#9caea9", "#dad2bc"] },
  },

  // === THEMES ===
  {
    name: "Lavender Dreams",
    description: "Soft purple theme for a calming experience",
    category: "themes",
    rarity: "common",
    price: 100,
    imageUrl: null,
    metadata: { primary: "#9b5de5", secondary: "#f15bb5", accent: "#fee440" },
  },
  {
    name: "Ocean Breeze",
    description: "Cool blue tones for clarity and focus",
    category: "themes",
    rarity: "common",
    price: 100,
    imageUrl: null,
    metadata: { primary: "#00b4d8", secondary: "#0077b6", accent: "#90e0ef" },
  },
  {
    name: "Forest Serenity",
    description: "Natural greens for grounding and peace",
    category: "themes",
    rarity: "rare",
    price: 175,
    imageUrl: null,
    metadata: { primary: "#2d6a4f", secondary: "#40916c", accent: "#95d5b2" },
  },
  {
    name: "Sunset Warmth",
    description: "Warm oranges and reds for energy",
    category: "themes",
    rarity: "rare",
    price: 175,
    imageUrl: null,
    metadata: { primary: "#ff6b35", secondary: "#f7c59f", accent: "#efefd0" },
  },
  {
    name: "Midnight Mode",
    description: "Deep dark theme with neon accents",
    category: "themes",
    rarity: "epic",
    price: 350,
    imageUrl: null,
    metadata: { primary: "#0d1b2a", secondary: "#1b263b", accent: "#e0e1dd", neon: "#00ff88" },
  },
  {
    name: "Cotton Candy",
    description: "Playful pink and blue pastels",
    category: "themes",
    rarity: "rare",
    price: 200,
    imageUrl: null,
    metadata: { primary: "#ff99c8", secondary: "#a9def9", accent: "#fcf6bd" },
  },

  // === AVATAR ACCESSORIES ===
  {
    name: "Harmony Headband",
    description: "A glowing headband radiating peaceful energy",
    category: "avatar_accessories",
    rarity: "rare",
    price: 200,
    imageUrl: null,
    metadata: { slot: "head", color: "#9b5de5", glow: true },
  },
  {
    name: "Empathy Earrings",
    description: "Crystal earrings that shimmer with understanding",
    category: "avatar_accessories",
    rarity: "rare",
    price: 175,
    imageUrl: null,
    metadata: { slot: "ears", color: "#f72585", sparkle: true },
  },
  {
    name: "Wisdom Glasses",
    description: "Stylish frames for the thoughtful communicator",
    category: "avatar_accessories",
    rarity: "common",
    price: 100,
    imageUrl: null,
    metadata: { slot: "eyes", style: "round", color: "#4361ee" },
  },
  {
    name: "Peace Pendant",
    description: "A calming necklace with a peace symbol",
    category: "avatar_accessories",
    rarity: "common",
    price: 75,
    imageUrl: null,
    metadata: { slot: "neck", symbol: "peace", color: "#4cc9f0" },
  },
  {
    name: "Mindful Crown",
    description: "A floating crown for the enlightened",
    category: "avatar_accessories",
    rarity: "legendary",
    price: 500,
    imageUrl: null,
    metadata: { slot: "head", style: "crown", color: "#ffd700", glow: true, float: true },
  },
  {
    name: "Serene Scarf",
    description: "A flowing scarf representing inner calm",
    category: "avatar_accessories",
    rarity: "common",
    price: 80,
    imageUrl: null,
    metadata: { slot: "neck", color: "#a8dadc", flow: true },
  },
  {
    name: "Balance Bow",
    description: "A cute bow symbolizing emotional balance",
    category: "avatar_accessories",
    rarity: "common",
    price: 60,
    imageUrl: null,
    metadata: { slot: "head", color: "#ffafcc" },
  },
  {
    name: "Focus Frames",
    description: "Sleek rectangular glasses for concentration",
    category: "avatar_accessories",
    rarity: "rare",
    price: 150,
    imageUrl: null,
    metadata: { slot: "eyes", style: "rectangular", color: "#023047" },
  },

  // === PROFILE DECORATIONS ===
  {
    name: "Sparkle Frame",
    description: "A shimmering frame around your profile",
    category: "profile_decorations",
    rarity: "common",
    price: 100,
    imageUrl: null,
    metadata: { type: "frame", effect: "sparkle", color: "#ffd700" },
  },
  {
    name: "Rainbow Aura",
    description: "A colorful aura surrounding your avatar",
    category: "profile_decorations",
    rarity: "epic",
    price: 400,
    imageUrl: null,
    metadata: { type: "aura", effect: "rainbow", animated: true },
  },
  {
    name: "Floating Hearts",
    description: "Cute hearts float around your profile",
    category: "profile_decorations",
    rarity: "rare",
    price: 175,
    imageUrl: null,
    metadata: { type: "particles", effect: "hearts", color: "#ff69b4" },
  },
  {
    name: "Star Trail",
    description: "Sparkling stars follow your avatar",
    category: "profile_decorations",
    rarity: "rare",
    price: 200,
    imageUrl: null,
    metadata: { type: "trail", effect: "stars", color: "#ffd700" },
  },
  {
    name: "Zen Circles",
    description: "Calm rippling circles emanate from your avatar",
    category: "profile_decorations",
    rarity: "common",
    price: 125,
    imageUrl: null,
    metadata: { type: "aura", effect: "ripple", color: "#90e0ef" },
  },
  {
    name: "Butterfly Garden",
    description: "Beautiful butterflies flutter around you",
    category: "profile_decorations",
    rarity: "epic",
    price: 350,
    imageUrl: null,
    metadata: { type: "particles", effect: "butterflies", animated: true },
  },

  // === PARTICLE EFFECTS ===
  {
    name: "Peaceful Petals",
    description: "Soft flower petals drift across your screen",
    category: "particle_effects",
    rarity: "rare",
    price: 250,
    imageUrl: null,
    metadata: { type: "petals", colors: ["#ffb7c5", "#ffc8dd", "#cdb4db"] },
  },
  {
    name: "Starlight",
    description: "Twinkling stars illuminate your space",
    category: "particle_effects",
    rarity: "common",
    price: 100,
    imageUrl: null,
    metadata: { type: "stars", colors: ["#ffffff", "#ffd700"] },
  },
  {
    name: "Fireflies",
    description: "Magical fireflies dance in the darkness",
    category: "particle_effects",
    rarity: "epic",
    price: 300,
    imageUrl: null,
    metadata: { type: "fireflies", colors: ["#ffff00", "#00ff00"], glow: true },
  },
  {
    name: "Snowfall",
    description: "Gentle snowflakes for a winter wonderland",
    category: "particle_effects",
    rarity: "rare",
    price: 175,
    imageUrl: null,
    metadata: { type: "snow", colors: ["#ffffff", "#e0e0e0"] },
  },
  {
    name: "Bubbles",
    description: "Playful bubbles float through the air",
    category: "particle_effects",
    rarity: "common",
    price: 75,
    imageUrl: null,
    metadata: { type: "bubbles", colors: ["#87ceeb", "#add8e6", "#b0e0e6"] },
  },

  // === SOUND BADGES (special notification sounds) ===
  {
    name: "Chime of Clarity",
    description: "A gentle chime for notifications",
    category: "sound_badges",
    rarity: "common",
    price: 50,
    imageUrl: null,
    metadata: { soundType: "chime", tone: "bright" },
  },
  {
    name: "Nature Whisper",
    description: "Soft forest sounds for alerts",
    category: "sound_badges",
    rarity: "rare",
    price: 150,
    imageUrl: null,
    metadata: { soundType: "nature", tone: "forest" },
  },
  {
    name: "Ocean Wave",
    description: "Soothing wave sounds for notifications",
    category: "sound_badges",
    rarity: "rare",
    price: 150,
    imageUrl: null,
    metadata: { soundType: "water", tone: "wave" },
  },

  // === QUOTES (displayed on profile) ===
  {
    name: "Inner Peace",
    description: '"Peace comes from within. Do not seek it without."',
    category: "quotes",
    rarity: "common",
    price: 25,
    imageUrl: null,
    metadata: { quote: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  },
  {
    name: "Growth Mindset",
    description: '"The only way to grow is to step outside your comfort zone."',
    category: "quotes",
    rarity: "common",
    price: 25,
    imageUrl: null,
    metadata: { quote: "The only way to grow is to step outside your comfort zone.", author: "Unknown" },
  },
  {
    name: "Empathy First",
    description: '"Understanding is the first step to acceptance."',
    category: "quotes",
    rarity: "rare",
    price: 75,
    imageUrl: null,
    metadata: { quote: "Understanding is the first step to acceptance.", author: "J.K. Rowling" },
  },
  {
    name: "Self Love",
    description: '"You yourself deserve your love and affection."',
    category: "quotes",
    rarity: "common",
    price: 30,
    imageUrl: null,
    metadata: { quote: "You yourself, as much as anybody in the entire universe, deserve your love and affection.", author: "Buddha" },
  },
];

export async function seedCosmeticItems(): Promise<void> {
  console.log("Checking cosmetic items...");
  
  // Check if items already exist
  const existingItems = await db.select().from(cosmeticItems).limit(1);
  
  if (existingItems.length > 0) {
    console.log("Cosmetic items already seeded, skipping...");
    return;
  }
  
  console.log("Seeding cosmetic items...");
  
  for (const item of COSMETIC_ITEMS) {
    await db.insert(cosmeticItems).values({
      name: item.name,
      description: item.description,
      category: item.category,
      rarity: item.rarity,
      price: item.price,
      imageUrl: item.imageUrl,
      metadata: item.metadata,
      isActive: true,
    });
  }
  
  console.log(`Seeded ${COSMETIC_ITEMS.length} cosmetic items`);
}
