export const questionBank = {
  workplace: [
    "How would you respond when your colleague takes credit for your work in a meeting?",
    "Describe how you feel when someone interrupts you during an important conversation.",
    "What would you say to a coworker who consistently misses deadlines affecting your work?",
    "How do you handle receiving harsh criticism from a supervisor?",
    "Practice asking for a raise with confidence and clarity.",
    "How would you address micromanagement from your boss?",
    "What do you say when a colleague makes an inappropriate joke?",
    "How do you decline additional work when you're already overwhelmed?",
    "Practice giving constructive feedback to a team member.",
    "How would you handle a conflict between two team members you manage?",
    "What would you say to a client who is being unreasonably demanding?",
    "How do you communicate when you've made a mistake at work?",
    "Practice negotiating flexible work arrangements with your manager.",
    "How would you respond to workplace gossip about yourself?",
    "What do you say when you disagree with a decision from leadership?",
  ],
  relationships: [
    "How do you express your needs when your partner isn't meeting them?",
    "Practice having a conversation about finances with your partner.",
    "What would you say when you feel unheard in your relationship?",
    "How do you apologize sincerely after hurting someone you love?",
    "Practice discussing future plans when you and your partner have different visions.",
    "How would you address jealousy in your relationship?",
    "What do you say when you need more quality time together?",
    "How do you communicate during an argument without escalating?",
    "Practice expressing appreciation for your partner regularly.",
    "How would you bring up a sensitive topic that's been bothering you?",
    "What do you say when your partner's family is overstepping boundaries?",
    "How do you discuss intimacy issues with compassion?",
    "Practice rebuilding trust after it's been broken.",
    "How would you express feeling overwhelmed by household responsibilities?",
    "What do you say when you need space without hurting your partner?",
  ],
  boundaries: [
    "How do you say no to a friend's request without feeling guilty?",
    "Practice setting limits with a family member who constantly criticizes you.",
    "What would you say when someone shares too much personal information too soon?",
    "How do you maintain boundaries with an ex who keeps reaching out?",
    "Practice declining an invitation when you need time alone.",
    "How would you address someone who borrows things and never returns them?",
    "What do you say when a neighbor is being too nosy?",
    "How do you set boundaries around your phone and availability?",
    "Practice communicating your limits in a new friendship.",
    "How would you respond when someone dismisses your boundaries?",
    "What do you say to someone who guilt-trips you for setting limits?",
    "How do you establish boundaries with a demanding parent?",
    "Practice saying no to a volunteer commitment you can't handle.",
    "How would you address someone who constantly asks for favors?",
    "What do you say when someone crosses a boundary you've already set?",
  ],
  empathy: [
    "How would you comfort a friend going through a difficult breakup?",
    "Practice listening without trying to solve the problem.",
    "What would you say to someone who just received bad news?",
    "How do you validate someone's feelings even when you disagree?",
    "Practice responding to a friend who is venting about their job.",
    "How would you support a family member dealing with grief?",
    "What do you say when someone shares their struggles with mental health?",
    "How do you show empathy to a child who is upset?",
    "Practice being present for someone without offering advice.",
    "How would you respond to a friend who feels like a failure?",
    "What do you say to comfort someone dealing with illness?",
    "How do you acknowledge someone's pain without minimizing it?",
    "Practice offering support to a colleague going through a tough time.",
    "How would you help a friend process their emotions?",
    "What do you say when you don't know what to say?",
  ],
  negotiation: [
    "Practice negotiating a better price on a major purchase.",
    "How would you negotiate a project deadline that seems unrealistic?",
    "What do you say when trying to reach a compromise in a family decision?",
    "How do you negotiate household chores with your partner?",
    "Practice asking for what you want while respecting the other person's needs.",
    "How would you negotiate vacation time with your employer?",
    "What do you say when both parties have valid but conflicting interests?",
    "How do you find middle ground in a dispute with a neighbor?",
    "Practice negotiating bedtime rules with your children.",
    "How would you handle negotiating a contract with a vendor?",
    "What do you say when you feel like you're always the one compromising?",
    "How do you negotiate responsibilities in a group project?",
    "Practice finding win-win solutions in everyday disagreements.",
    "How would you negotiate terms in a rental agreement?",
    "What do you say when negotiations reach an impasse?",
  ],
  accountability: [
    "How do you take responsibility when you've forgotten an important commitment?",
    "Practice apologizing without making excuses.",
    "What would you say after realizing you hurt someone unintentionally?",
    "How do you own your part in a misunderstanding?",
    "Practice acknowledging a mistake to your team.",
    "How would you address your role in a project failure?",
    "What do you say when you need to admit you were wrong?",
    "How do you take accountability for missing a deadline?",
    "Practice having an honest conversation about a lie you told.",
    "How would you apologize for losing your temper?",
    "What do you say when you've let a friend down?",
    "How do you make amends after breaking a promise?",
    "Practice owning your emotions instead of blaming others.",
    "How would you address past behavior you're not proud of?",
    "What do you say when taking responsibility for a difficult situation?",
  ],
  feedback: [
    "How do you give feedback to a friend about their behavior?",
    "Practice delivering constructive criticism to a colleague.",
    "What would you say when offering honest feedback about someone's work?",
    "How do you provide feedback without hurting someone's feelings?",
    "Practice receiving feedback without becoming defensive.",
    "How would you give performance feedback to a team member?",
    "What do you say when asked for your honest opinion on something?",
    "How do you offer feedback to a supervisor?",
    "Practice balancing positive and constructive feedback.",
    "How would you address consistent underperformance with compassion?",
    "What do you say when feedback is hard to hear?",
    "How do you give feedback about personal hygiene sensitively?",
    "Practice asking for feedback on your own performance.",
    "How would you provide feedback in a mentoring relationship?",
    "What do you say when giving feedback that might be unpopular?",
  ],
  needs: [
    "How do you express your need for support when you're struggling?",
    "Practice asking for help without feeling like a burden.",
    "What would you say when you need more affection from your partner?",
    "How do you communicate your need for alone time?",
    "Practice expressing your emotional needs clearly.",
    "How would you ask for what you need in a friendship?",
    "What do you say when your needs conflict with someone else's?",
    "How do you advocate for your needs in healthcare settings?",
    "Practice stating your needs without apologizing for them.",
    "How would you express your need for recognition at work?",
    "What do you say when you need space to process your emotions?",
    "How do you communicate your need for better communication?",
    "Practice asking for accommodations without feeling guilty.",
    "How would you express your need for more respect?",
    "What do you say when you need someone to listen without fixing?",
  ],
};

export const categories = Object.keys(questionBank) as Array<keyof typeof questionBank>;

export function getRandomQuestion(category: keyof typeof questionBank): string {
  const questions = questionBank[category];
  return questions[Math.floor(Math.random() * questions.length)];
}

export function getRandomQuestions(category: keyof typeof questionBank, count: number): string[] {
  const questions = [...questionBank[category]];
  const selected: string[] = [];
  for (let i = 0; i < count && questions.length > 0; i++) {
    const index = Math.floor(Math.random() * questions.length);
    selected.push(questions.splice(index, 1)[0]);
  }
  return selected;
}
